CREATE OR REPLACE TYPE TYPE_ROW_TUPLE_PAIR AS OBJECT (
   A   VARCHAR2(250),
   B   VARCHAR2(250),
   CONSTRUCTOR FUNCTION TYPE_ROW_TUPLE_PAIR RETURN SELF AS RESULT
);
/

CREATE OR REPLACE TYPE BODY TYPE_ROW_TUPLE_PAIR
AS
   CONSTRUCTOR FUNCTION TYPE_ROW_TUPLE_PAIR RETURN SELF AS RESULT
   AS
    BEGIN
          RETURN;
    END;
END;
/

CREATE OR REPLACE TYPE TYPE_TAB_TUPLE_PAIR AS TABLE OF TYPE_ROW_TUPLE_PAIR;
/

CREATE OR REPLACE TYPE TYPE_ROW_TUPLE_TRIPLET AS OBJECT
(
   A VARCHAR2 (250),
   B VARCHAR2 (250),
   C VARCHAR2 (250),
   CONSTRUCTOR FUNCTION TYPE_ROW_TUPLE_TRIPLET
      RETURN SELF AS RESULT
);
/

CREATE OR REPLACE TYPE BODY TYPE_ROW_TUPLE_TRIPLET
AS
   CONSTRUCTOR FUNCTION TYPE_ROW_TUPLE_TRIPLET
      RETURN SELF AS RESULT
   AS
    BEGIN
          RETURN;
    END;
END;
/

CREATE OR REPLACE TYPE TYPE_TAB_TUPLE_TRIPLET AS TABLE OF TYPE_ROW_TUPLE_TRIPLET;
/

CREATE OR REPLACE TYPE TYPE_ROW_MESSAGE FORCE AS OBJECT (
      CodeLevel          VARCHAR2(1)
      , Message          VARCHAR2(2500)
      , CodeMessage      VARCHAR2(5)
      , CONSTRUCTOR FUNCTION TYPE_ROW_MESSAGE RETURN SELF AS RESULT
);
/

CREATE OR REPLACE TYPE BODY TYPE_ROW_MESSAGE
AS
   CONSTRUCTOR FUNCTION TYPE_ROW_MESSAGE RETURN SELF AS RESULT
   AS
    BEGIN
      RETURN;
    END;
END;
/

CREATE OR REPLACE TYPE TYPE_TAB_MESSAGE AS TABLE OF TYPE_ROW_MESSAGE;
/


CREATE OR REPLACE PACKAGE PKG_ADN_COMMANDE
IS
    PROCEDURE CONTROLE_SAILLIE_GENITEUR(PN_IdChien IN NUMBER, PC_OnSexe IN VARCHAR2, PT_Message IN OUT TYPE_TAB_MESSAGE);
END PKG_ADN_COMMANDE;
/

CREATE OR REPLACE PACKAGE BODY PKG_ADN_COMMANDE
AS
--
PROCEDURE CONTROLE_SAILLIE_GENITEUR(PN_IdChien IN NUMBER, PC_OnSexe IN VARCHAR2, PT_Message IN OUT TYPE_TAB_MESSAGE)
IS
   MissingEmpreinteAdn EXCEPTION;
BEGIN
--
   IF PN_IdChien = 11 THEN
      RAISE MissingEmpreinteAdn;
   END IF;
   --
   PT_Message.EXTEND;
   PT_Message(PT_Message.LAST) := TYPE_ROW_MESSAGE (
       'W'
       , 'Message de test'
       , 'SA018'
   )
   ;
EXCEPTION   
   WHEN OTHERS THEN  
      NULL;   
END CONTROLE_SAILLIE_GENITEUR;
--@
END PKG_ADN_COMMANDE;
/